### ISSUE TITLE
refactor code with go module

### ISSUE THREAD

**Issue by songjiayang** [gortc/stund#1]

**Comment by ernado** [comment]
@songjiayang 
oh, seems like your commits have no email :(

you can re-create a pull-request with base from `3f25148725439e0f465b467a20c3befe7986e3b5` so we can fix it and you will be in contributors

**Comment by songjiayang** [comment]
@ernado  After added my email to GitHub [settings/emails](https://github.com/settings/emails), everything is ok, so no need re-create pr.

<img width="575" alt="Screen Shot 2019-04-09 at 11 55 48 PM" src="https://user-images.githubusercontent.com/1459834/55815545-1e30ac00-5b23-11e9-8864-51f7b40c54e0.png">

**Comment by ernado** [comment]
Yes, thank you :)
You can close this issue if everything is OK now.
